#!/bin/sh

cd /var/lib/jenkins/jobs/BJTU-nodejs
cp -r workspace /../home/ubuntu/nodejsProject/BJTU-nodejs-project
cd /../home/ubuntu/nodejsProject/BJTU-nodejs-project
npm install --production
node app.js



<<!
ssh -tt app@APP.SERVER.IP.ADDRESS <<EOF
	cd ~/BJTU-nodejs-project
	get pull
	npm install --production
	forever restartall
	exit
EOF
!
